# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#from picamera2 import Picamera2
#from picamera2.previews.qt import QGlPicamera2
from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 725)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icones/lion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.gridMainWindow = QtWidgets.QWidget(MainWindow)
        self.gridMainWindow.setObjectName("gridMainWindow")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridMainWindow)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayoutButton = QtWidgets.QHBoxLayout()
        self.verticalLayoutButton.setObjectName("verticalLayoutButton")
        self.botaoComecar = QtWidgets.QPushButton(self.gridMainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botaoComecar.sizePolicy().hasHeightForWidth())
        self.botaoComecar.setSizePolicy(sizePolicy)
        self.botaoComecar.setMinimumSize(QtCore.QSize(50, 50))
        self.botaoComecar.setStyleSheet("background-color: transparent;\n"
"border: none;\n"
"image: url(:/icones/comecar.png);\n"
"")
        self.botaoComecar.setText("")
        self.botaoComecar.setObjectName("botaoComecar")
        self.verticalLayoutButton.addWidget(self.botaoComecar)
        self.gridLayout_4.addLayout(self.verticalLayoutButton, 1, 1, 1, 1)
        self.horizontalLayoutProgress = QtWidgets.QVBoxLayout()
        self.horizontalLayoutProgress.setObjectName("horizontalLayoutProgress")
        self.progresslabel = QtWidgets.QLabel(self.gridMainWindow)
        self.progresslabel.setObjectName("progresslabel")
        self.horizontalLayoutProgress.addWidget(self.progresslabel)
        self.progressBar_tempo = QtWidgets.QProgressBar(self.gridMainWindow)
        self.progressBar_tempo.setAccessibleName("")
        self.progressBar_tempo.setAccessibleDescription("")
        self.progressBar_tempo.setProperty("value", 0)
        self.progressBar_tempo.setObjectName("progressBar_tempo")
        self.horizontalLayoutProgress.addWidget(self.progressBar_tempo)
        self.gridLayout_4.addLayout(self.horizontalLayoutProgress, 1, 0, 1, 1)
        self.gridPreview = QtWidgets.QGridLayout()
        self.gridPreview.setObjectName("gridPreview")
        self.preview_local = QtWidgets.QLabel(self.gridMainWindow)              #
        self.preview_local.setStyleSheet("background-color: rgb(0, 0, 0);")     #
        self.preview_local.setObjectName("preview_local")                       #
        self.gridPreview.addWidget(self.preview_local, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridPreview, 0, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 8)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.gridLayout_4.setRowStretch(0, 15)
        self.gridLayout_4.setRowStretch(1, 3)
        MainWindow.setCentralWidget(self.gridMainWindow)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 26))
        self.menubar.setObjectName("menubar")
        self.menuArquivos = QtWidgets.QMenu(self.menubar)
        self.menuArquivos.setObjectName("menuArquivos")
        self.menuConfigura_es = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es.setObjectName("menuConfigura_es")
        self.menuResultados = QtWidgets.QMenu(self.menubar)
        self.menuResultados.setObjectName("menuResultados")
        self.menuFoco = QtWidgets.QMenu(self.menubar)
        self.menuFoco.setObjectName("menuFoco")
        self.menuVari_veis_do_ambiente = QtWidgets.QMenu(self.menubar)
        self.menuVari_veis_do_ambiente.setObjectName("menuVari_veis_do_ambiente")
        self.menuConfigura_es_2 = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es_2.setObjectName("menuConfigura_es_2")
        self.menuConfigura_es_Avan_adas = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es_Avan_adas.setObjectName("menuConfigura_es_Avan_adas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icones/salvar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalvar.setIcon(icon1)
        self.actionSalvar.setObjectName("actionSalvar")
        self.menubar.addAction(self.menuArquivos.menuAction())
        self.menubar.addAction(self.menuConfigura_es.menuAction())
        self.menubar.addAction(self.menuFoco.menuAction())
        self.menubar.addAction(self.menuConfigura_es_2.menuAction())
        self.menubar.addAction(self.menuConfigura_es_Avan_adas.menuAction())
        self.menubar.addAction(self.menuVari_veis_do_ambiente.menuAction())
        self.menubar.addAction(self.menuResultados.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "lion"))
        self.progresslabel.setText(_translate("MainWindow", "Analisando ..."))
        #self.preview_local.setText(_translate("MainWindow", "TextLabel"))            #
        self.menuArquivos.setTitle(_translate("MainWindow", "Salvar"))
        self.menuConfigura_es.setTitle(_translate("MainWindow", "Patches"))
        self.menuResultados.setTitle(_translate("MainWindow", "Resultados"))
        self.menuFoco.setTitle(_translate("MainWindow", "Foco"))
        self.menuVari_veis_do_ambiente.setTitle(_translate("MainWindow", "Variáveis do ambiente"))
        self.menuConfigura_es_2.setTitle(_translate("MainWindow", "Configurações"))
        self.menuConfigura_es_Avan_adas.setTitle(_translate("MainWindow", "Configurações avançadas"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
import py_GUIs.icones_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
